### ISSUE TITLE
请问此webui和原版区别表现在哪里？我不清楚成功替换没。

### ISSUE THREAD

**Issue by hot36952** [Lambholl/qb-webui#3]
我把包里的2个文件夹解压到webui设置指定的目录，强制刷新缓存了，但是界面和设置里没看出区别，我不清楚成功替换没。
#因为我是局域网免登录的，没看登录界面。
另外请问能不能增加查看日志的功能，类似荒野无灯的qb那种。

**Comment by Lambholl** [comment]
如果没登录页面的话，区别主要就是种子页面里面的日文标题种子会换成日标字体

日志的话，我没研究过，最近也比较忙，以后有空了可能会做一下吧
